"""empty message

Revision ID: e4288be57f24
Revises: 
Create Date: 2026-03-01 12:26:37.987522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4288be57f24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure_implant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('implant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['implant_id'], ['implant.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventory_item')
    with op.batch_alter_table('implant', schema=None) as batch_op:
        batch_op.alter_column('min_stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('implant', schema=None) as batch_op:
        batch_op.alter_column('min_stock',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('min_stock', sa.INTEGER(), nullable=True),
    sa.Column('supplier', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lot_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expiration_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date_added', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procedure_implant')
    op.drop_table('procedure')
    # ### end Alembic commands ###
